### ISSUE TITLE
Move Config Tab

### ISSUE THREAD

**Issue by sprankhub** [mediarox/module-checkout-street-number#1]
Thanks for this extension!

It is already debatable if it is necessary to have a custom tab in the system configuration. However, if you add one, could you at least move it elsewhere and not make it the first one? :)

![image](https://user-images.githubusercontent.com/930199/175028287-aba92ba8-57b3-499e-ae20-f714d145db18.png)

**Comment by sfritzsche** [comment]
We have actually discussed the "mediarox" menu item internally several times :) 
The colleague I do not want to mention here by name,) has started the module with this menu and somehow it stuck to it.

With the next change, however, I will adapt it and probably also sort thematically into an existing point :)

**Comment by sfritzsche** [comment]
@sprankhub Done. Don't forget to reset "bin/magento config:set checkout/options/split_street_into_name_and_number 1".
